### ISSUE TITLE
pra onde foi minha inscrição?

### ISSUE THREAD

**Issue by ghost** [suissa/Curso-JavaScript-Super-Sayajin-oficial#1]
Fala Jean,

Cara, onde foi parar inha inscrição do curso de JS SSJ??

**Comment by suissa** [comment]
Nem eu sei, pois aquele repositório foi bloqueado pelo Github!

![screen shot 2017-08-17 at 5 53 25 pm](https://user-images.githubusercontent.com/75607/29544746-9d3926f0-86c0-11e7-88eb-29355d3b658c.png)

**Comment by ghost** [comment]
E agora, como que faço com o curso?

Vai rolar ainda? Vai ter reembolso? Como que é?

**Comment by suissa** [comment]
Já está rolando o curso https://www.youtube.com/watch?v=8ZseJ3aniPE&list=PL77JVjKTJT2ieRNlfVYqzd95ultVcR1q2

**Comment by suissa** [comment]
Nosso repo oficial voltou!!!! https://github.com/suissa/Curso-JavaScript-Super-Sayajin

Pode mandar o exercicio p/ ele por favor, na mesma issue sua, por favor renomeie o título dela para o seu nick do Github.
