### ISSUE TITLE
iae suissa

### ISSUE THREAD

**Issue by caiomyrapereira** [suissa/Curso-JavaScript-Super-Sayajin-oficial#2]
o exercícios  , enviar aqui? desculpa não sei mexer no github.

**Comment by suissa** [comment]
Isso, porém crei uma ISSUE nova com o título do seu nick aqui no github.

Nessa ISSUE vc colocara tudo q for pedido nas aulas. 

Os códigos vc deve usar o gist.github.com para isso e colocar apenas o LINK na sua issue.
