### ISSUE TITLE
RafaelaMiranda

### ISSUE THREAD

**Issue by rafaelamiranda** [suissa/Curso-JavaScript-Super-Sayajin-oficial#3]
**Link do repositório:** https://github.com/RafaelaMiranda/Curso-JavaScript-Super-Sayajin

**Comment by suissa** [comment]
Nosso repo oficial voltou!!!! https://github.com/suissa/Curso-JavaScript-Super-Sayajin

Pode mandar o exercicio p/ ele por favor, na mesma issue sua, por favor renomeie o título dela para o seu nick do Github.
