### ISSUE TITLE
CaioMyra

### ISSUE THREAD

**Issue by caiomyrapereira** [suissa/Curso-JavaScript-Super-Sayajin-oficial#4]
https://github.com/caiomyrapereira/Curso-JavaScript-Super-Sayajin-N-vel-1-M-dulo-1-exerc-cios

**Comment by suissa** [comment]
Nosso repo oficial voltou!!!! https://github.com/suissa/Curso-JavaScript-Super-Sayajin

Pode mandar o exercicio p/ ele por favor, na mesma issue sua, por favor renomeie o título dela para o seu nick do Github.
