### ISSUE TITLE
ViniciusMazzeo

### ISSUE THREAD

**Issue by viniciusmazzeo** [suissa/Curso-JavaScript-Super-Sayajin-oficial#5]
https://github.com/viniciusmazzeo/Curso-JavaScript-Super-Sayajin-N-vel-1-M-dulo-1-exerc-cios/tree/master/aula_01

**Comment by suissa** [comment]
Nosso repo oficial voltou!!!! https://github.com/suissa/Curso-JavaScript-Super-Sayajin

Pode mandar o exercicio p/ ele por favor, na mesma issue sua, por favor renomeie o título dela para o seu nick do Github.
