### ISSUE TITLE
JeyzielGama

### ISSUE THREAD

**Issue by jeyziel** [suissa/Curso-JavaScript-Super-Sayajin-oficial#6]
**Curso-JavaScript-Super-Sayajin-Nível-1-Módulo-1-exercícios-aula1
Raw**
https://gist.github.com/jeyziel/f35322287686909dcfb5e43c63db617b

**Comment by suissa** [comment]
Nosso repo oficial voltou!!!! https://github.com/suissa/Curso-JavaScript-Super-Sayajin

Pode mandar o exercicio p/ ele por favor, na mesma issue sua, por favor renomeie o título dela para o seu nick do Github.
